name: dart_numerics
description: An ultimate numerical package for Dart for professional and every day use.
version: 0.0.5-SNAPSHOT
homepage: https://github.com/zlumyo/dart_numerics
author: Vladimir Ivanov <zlumyo@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  tuple: ^1.0.2

dev_dependencies:
  test: ^1.0.0
