name: dart_numerics
description: An ultimate numerical package for Dart.
version: 0.0.2
homepage: https://github.com/zlumyo/dart_numerics
author: Vladimir Ivanov <zlumyo@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dev_dependencies:
  test: ^1.0.0
